### ISSUE TITLE
Error on composer update

### ISSUE THREAD

**Issue by edgardmessias** [Codeception/c3#30]
If run `composer update`, show this error:
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Composer\DependencyResolver\Operation\InstallOperation::getTargetPackage()
```

If run `composer install`, not show error:

**Comment by dereuromark** [comment]
Related to https://github.com/Codeception/c3/commit/8adf2a1699e1f0215f24b27889bf0478f5c77d52#commitcomment-21634132
