### ISSUE TITLE
Error on composer update

### ISSUE THREAD

**Issue by Nimesin-Boxmark** [Codeception/c3#34]
On last update, 2.0.13, when I try to composer update, got following error:
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function Codeception\c3\Installer::copyC3(), 0 passed in C:\www\PPA_DDD\vendor\codeception\c3\Installer.php on line 88 and exactly 1 expected in C:\www\PPA_DDD\vendor\codeception\c3\Installer.php:62
Stack trace:
#0 C:\www\PPA_DDD\vendor\codeception\c3\Installer.php(88): Codeception\c3\Installer->copyC3()
#1 [internal function]: Codeception\c3\Installer->askForUpdate(Object(Composer\Installer\PackageEvent))
#2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php(608): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('post-package-up...', true, Ob in C:\www\PPA_DDD\vendor\codeception\c3\Installer.php on line 62`

There is a missing $event as parameter in line 88 of Installer.php

**Comment by dereuromark** [comment]
Same thing here :/

**Comment by edgardmessias** [comment]
Replace `$this->copyC3();` with `$this->copyC3($event);` in `Installer.php`
