### ISSUE TITLE
Minimal dependences

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/c3#39]
So... `c3.php` don't run without `Codeception\Codeception`

Add  `Codeception` to composer `require-dev` is owerkill. 

O_O

Can you get minimal requirements for coverage acceptance tests? Unit and Functional tests coverage I will run using docker image of codeception.

Or I must use another way?

**Comment by Naktibalda** [comment]
c3.php can load Codeception for [codecept.phar](https://github.com/Codeception/c3/blob/2.0/c3.php#L64-L74) file so composer dependency isn't necessary.
And it is a bit of overkill to install c3 with composer because it consists of a single file.
Though I've never used c3.

**Comment by bscheshirwork** [comment]
@Naktibalda so... May be you can help me please? How to check codecoverage for acceptance test?
