### ISSUE TITLE
Don't work with suite configuration

### ISSUE THREAD

**Issue by komandakycto** [Codeception/c3#50]
I try run coverage count by command:
```sh
php vendor/bin/codecept run -c api --debug --coverage
```
And nothing work. I see in Response error: **Notice: Undefined variable: settings in /var/www/html/c3.php on line 249** If I parse Exception on 241 line I see message: "Suite api was not loaded" because `self::suites` is empty in vendor/codeception/base/src/Codeception/Configuration.php:307. 

When s3.php run `\Codeception\Configuration::suiteSettings($suite, \Codeception\Configuration::config())` without configuration file we see that `config` method return `self::$config` and don't run `self::loadSuites();` below. It is cause why I see that my suit was not loaded.

My composer versions:,
    "codeception/base": "^2.2.3",
    "codeception/verify": "~0.3.1",
    "phpunit/phpunit": "5.7.27",
    "codeception/c3": "2.*"

My project structure
-root
---api
----tests
------api/
------functional/
------unit/
------api.suite.yml
------functional.suite.yml
------unit.suite.yml
----codeception.yml
--backend/
--common/
-codeception.yml

**Comment by komandakycto** [comment]
In s3.php in __c3_factory() function run `\Codeception\Configuration::config()` and load global config. In config() function execute only first lines:
```php
if (!$configFile && self::$config) {
       return self::$config;
}
```

**Comment by Naktibalda** [comment]
It returns cached result if `config` method is called multiple times.

**Comment by Naktibalda** [comment]
The only way to get config without suites is if you `include` setting is present and `paths: tests:` is missing in codeception.yml.
https://github.com/Codeception/base/blob/2.2.3/src/Codeception/Configuration.php#L183-L184

Which is quite likely with your directory structure.

**Comment by komandakycto** [comment]
Thanks, it was cause of exception like "Suite api was not loaded". But after fix, I catch another error =)
