### ISSUE TITLE
Composer Plugin API is deprecated

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/c3#52]
I noticed this warning in [failed build](https://travis-ci.org/Codeception/c3/jobs/591447574)
> Deprecation warning: require.composer-plugin-api is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

**Comment by robwilde** [comment]
Causing a big problem with Composer 2.*

**Comment by Tchiller** [comment]
This is the warning, we are getting when trying to use compser 2

`The "codeception/c3" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.`

**Comment by vctls** [comment]
Just tested v2.6.0 on my CI and it's working! ❤
