### ISSUE TITLE
Probleme with pcov

### ISSUE THREAD

**Issue by AllanFousse** [Codeception/c3#60]
C3 doesn't seem to work with pcov, while everything works fine with xdebug.

Same php code, just the choice of pcov or xdebug in php.ini

Pcov and Xdebug works well for unit tests,

**Comment by Sharnw** [comment]
Having the same issue. 

Pcov and xdebug both work fine for unitt tests. 

For acceptance tests Pcov returns '0.00% (0/249955)' line coverage while xdebug actually works.

**Comment by Naktibalda** [comment]
I can confirm that `pcov.directory` setting is required for pcov code coverage to work, I just added it to Github Actions of this repository to make tests pass: https://github.com/Codeception/c3/pull/69
