### ISSUE TITLE
Fatal error from c3.php file

### ISSUE THREAD

**Issue by Pi-George** [Codeception/c3#67]
Stepping through my codeception Actor, my code uses amOnPage() to try and load the login page, then grabResponse() and I get this:

```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Codeception\codecept_is_path_absolute() in /srv/www/vendor/codeception/codeception/src/Codeception/Configuration.php:529
Stack trace:
#0 /srv/www/vendor/codeception/codeception/src/Codeception/Configuration.php(557): Codeception\Configuration::outputDir()
#1 /srv/www/c3.php(122): Codeception\Configuration::logDir()
#2 /srv/www/app-loader.php(46): include('...')
#3 /srv/www/public/index.php(2): require_once('...')
#4 {main}
  thrown in <b>/srv/www/vendor/codeception/codeception/src/Codeception/Configuration.php</b> on line <b>529</b><br />

```

It's been an issue since we upgraded to XDebug 3 and PHP 8 and only happens if running codeception with code coverage enabled

It appears to be an autoload issue of some kind. Here's my app-loader.php code (up until where it fails)
```

<?php // phpcs:ignore

use Bugsnag\Client as BugsnagClient;
use Pi\Core\Bootstrap\Autoloader;
use Pi\Core\Bootstrap\ConfigBuilder;
use Pi\Core\Bootstrap\ContainerBootstrap;
use Pi\Core\Bootstrap\EntryPointResolver;
use Pi\Core\Bootstrap\SessionInitialiser;
use Pi\Core\Bootstrap\ZendApplicationBootstrapProxy;
use Pi\Core\ErrorHandling\ErrorHandler;

/**
 * Need to set this here as some of the logic which executes before bootstrap requires a date
 */
date_default_timezone_set('UTC');

/**
 * Base directory of entire application
 */
define('APPLICATION_ROOT', dirname(__FILE__));

/**
 * Location of the "application" directory - required by Zend
 */
define('APPLICATION_PATH', APPLICATION_ROOT . '/application');

/**
 * Defines whether the app was invoked through the web or command line
 */
define('INVOCATION_MODE', PHP_SAPI === 'cli' ? 'cli' : 'http');

require_once APPLICATION_ROOT . '/vendor/autoload.php';
require_once APPLICATION_PATH . '/configs/environment.php';

// We need our own autoloader to handle our non-psr-4 module structure
// It may make sense to load this in composer.json instead
require APPLICATION_PATH . '/modules/core/code/Bootstrap/Autoloader.php';
spl_autoload_register([new Autoloader(), 'autoload']);

$entryPoint = (new EntryPointResolver())->determineEntryPoint();

$config = (new ConfigBuilder())->initConfig($entryPoint);

if ($config->codeception->codecoverage === '1') {
    define('C3_CODECOVERAGE_ERROR_LOG_FILE', APPLICATION_ROOT . '/var/log/c3_error.log');
    include APPLICATION_ROOT . '/c3.php';
    define('MY_APP_STARTED', true);
}
```

**Comment by Naktibalda** [comment]
@Pi-George Could you try to use this c3.php file instead and let me know if it works?
https://raw.githubusercontent.com/Codeception/c3/issue-67/c3.php

**Comment by Pi-George** [comment]
I updated to the latest c3 file after your recent merge and new hotfix release. Unfortunately I now just get a completely different error:

<br />
<b>Fatal error</b>:  Uncaught SebastianBergmann\CodeCoverage\Driver\Xdebug3NotEnabledException: XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set in /srv/www/vendor/phpunit/php-code-coverage/src/Driver/Xdebug3Driver.php:65
Stack trace:
#0 /srv/www/vendor/phpunit/php-code-coverage/src/Driver/Selector.php(43): SebastianBergmann\CodeCoverage\Driver\Xdebug3Driver-&gt;__construct()
#1 /srv/www/vendor/phpunit/php-code-coverage/src/Driver/Driver.php(82): SebastianBergmann\CodeCoverage\Driver\Selector-&gt;forLineCoverage()
#2 /srv/www/c3.php(249): SebastianBergmann\CodeCoverage\Driver\Driver::forLineCoverage()
#3 /srv/www/c3.php(362): __c3_factory()
#4 /srv/www/app-loader.php(46): include('...')
#5 /srv/www/public/index.php(2): require_once('...')
#6 {main}
  thrown in <b>/srv/www/vendor/phpunit/php-code-coverage/src/Driver/Xdebug3Driver.php</b> on line <b>65</b><br />

XDebug mode is set to coverage (in my cli, using $XDEBUG_MODE=coverage,debug). I'm unsure if this is a C3 issue where it isn't setting the xdebug mode correctly or if it's completely unrelated to this project.

**Comment by Naktibalda** [comment]
Xdebug configuration must be set in php.ini file of the website you are testing : https://xdebug.org/docs/code_coverage#mode

**Comment by Pi-George** [comment]
I just tried setting the mode to coverage,debug in the php.ini and I got the same error. I've confirmed with `php -i | grep xdebug.mode` that I didn't mess up the config somehow

**Comment by Pi-George** [comment]
```
array (
  'cookie' => 'CODECEPTION_CODECOVERAGE={"CodeCoverage":"pageSmokeTester","CodeCoverage_Suite":"smoke","CodeCoverage_Config":null}',
  'user-agent' => 'Symfony BrowserKit',
  'host' => 'localhost',
  'x-codeception-codecoverage' => 'pageSmokeTester',
  'x-codeception-codecoverage-suite' => 'smoke',
  'x-codeception-codecoverage-config' => NULL,
)
```
Seems it really doesn't like x-codeception-codecoverage-config having a NULL value. Is there an easy way to give it a value?

**Comment by Pi-George** [comment]
I can't find anything in the documentation on remote_config. But I can see that it default to null. Trying random values of my own doesn't seem to help at all as it just gives me slightly different errors, either from disallowed header formats or from codeception complaining about the values.

**Comment by Naktibalda** [comment]
It is odd that you get that header sent, Codeception only sets it if remote_config setting is not empty:

https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Coverage/Subscriber/LocalServer.php#L68-L69

**Comment by Pi-George** [comment]
Yeah, I've gone through that function with XDEBUG and it isn't even going into that if statement, it correctly skips lines 69-80. I think it's LN 188 in LocalServer.php which causes this, and then somewhere along the line the cookie values are somehow being changed into headers.

**Comment by Naktibalda** [comment]
You are right, that code is in c3.php https://github.com/Codeception/c3/blob/2.0/c3.php#L16-L30

**Comment by Pi-George** [comment]
Can we add an if statement to line 27, so it only adds the header if `is_string($value) && is_numeric($value)`

**Comment by Naktibalda** [comment]
`if (!empty($value))`

**Comment by Pi-George** [comment]
Sure that works too, thanks for all of your help by the way
